// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PortfolioAPI.Models;

#nullable disable

namespace PortfolioAPI.Migrations
{
    [DbContext(typeof(PortfolioDbContext))]
    [Migration("20260909194815_AddPortfolioProject")]
    partial class AddPortfolioProject
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PortfolioAPI.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GitHubUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LiveUrl")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("TechStack")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Work",
                            Description = "MERN application built to manage 15+ CSCI capstone projects, featuring metadata display and secure file upload/download.",
                            TechStack = "[\"MongoDB\",\"Express\",\"React\",\"Node.js\"]",
                            Title = "Capstone Project Management App"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Work",
                            Description = "ReactJS/Django/SQL application tracking 500+ campus devices, supporting GLBA compliance with data display, updates, and data analysis.",
                            TechStack = "[\"React\",\"Django\",\"SQL\"]",
                            Title = "Asset Inventory System"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Personal",
                            Description = "Mobile app built with React Native and Expo Go, deployed to AWS using Lambda for stat calculations, DynamoDB for score storage, and IAM for permissions.",
                            TechStack = "[\"React Native\",\"TypeScript\",\"AWS Lambda\",\"DynamoDB\"]",
                            Title = "Frisbee Golf Score Tracker"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Personal",
                            Description = "Windows installer automating software rollouts, with a ReactJS dashboard for role-based install permissions, running in a Dockerized SQL Server/C#/.NET environment.",
                            TechStack = "[\"C#\",\".NET\",\"Docker\",\"SQL Server\",\"React\"]",
                            Title = "Automated Software Package Installer"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Personal",
                            Description = "Full-stack portfolio site with an ASP.NET Core Web API backend, a React/TypeScript frontend, and an Azure SQL database, deployed on Azure Static Web Apps and App Service.",
                            GitHubUrl = "https://github.com/dgarstecki-dev/portfolio",
                            TechStack = "[\"C#\",\"ASP.NET Core\",\"React\",\"TypeScript\",\"Azure SQL\",\"Azure App Service\"]",
                            Title = "Portfolio Website"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
